[package]
name = "duma"
version = "0.1.0"
authors = ["Matt Gathu <mattgathu@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.31.2"
console = "0.7.5"
ftp = "3.0.1"
indicatif = "0.11.0"
num_cpus = "1.10.0"
reqwest = "0.9.11"

[dev-dependencies]
assert_cli = "0.4"
